---
title: "New Semester"
description: |
  A short description of the post.
author:
  - name: Rodney Dyer
    url: https://dyerlab.org
    affiliation: Center for Environmental Studies
    affiliation_url: https://ces.vcu.edu
    orcid_id: 0000-0003-4707-3453
date: 2016-01-11
output:
  distill::distill_article:
    self_contained: false
---




This semester has a ton of new content and opportunities in the Dyerlab. Here is a quick synopsis.

  * Teaching _Population Genetics_, should be a ton of fun.
  * Teaching the Distributed graduate seminar _Landscape Genetics_ again.
  * Starting a new eDNA project with VDOT and getting a new student associated with it.
  * Starting a new RadSEQ project on Protonotary Warblers and getting a new student to start in the fall.
  * Starting a new Landscape Genetics NSF-funded project on gypsy moths with the Johnson Lab.  Need a technician for this one as well.
  * The text _Applied Population Genetics_ should be released as an ebook.
  * Should be finishing up both Jameson’s and Chitra’s theses and submitting them for publication.
  * Moving into a new laboratory location and perhaps collapsing both our lab and the Verrelli lab into a single unit.
 
 
 
