---
title: "Functional connectivity and home range inferred at a microgeographic landscape genetics scale in a desert-dwelling rodent"
date: 2019-01-01
authors:
  - Alejandro Flores-Manzanero
  - Madisson A. Luna-Barcenas
  - Rodney J. Dyer
  - Ella Vazquez-Dominguez
description: "Gene flow in animals is limited or facilitated by different features within the landscape matrix they inhabit. The landscape representation in landscape genetics (LG) is traditionally modeled as resistance surfaces (RS), where novel optimization approaches are needed for assigning resistance values that adequately avoid subjectivity. Also, desert ecosystems and mammals are scarcely represented in LG studies. We addressed these issues by evaluating, at a microgeographic scale, the effect of landscape features on functional connectivity of the desert-dwelling Dipodomys merriami. We characterized genetic diversity and structure with microsatellites loci, estimated home ranges and movement of individuals using telemetry-one of the first with rodents, generated a set of individual and composite environmental surfaces based on hypotheses of variables influencing movement, and assessed how these variables relate to individual-based gene flow. Genetic diversity and structure results evidenced a family-induced pattern driven by first-order-related individuals, notably determining landscape genetic inferences. The vegetation cover and soil resistance optimized surface (NDVI) were the best-supported model and a significant predictor of individual genetic distance, followed by humidity and NDVI+humidity. Based on an accurate definition of thematic resolution, we also showed that vegetation is better represented as continuously (vs. categorically) distributed. Hence, with a nonsubjective optimization framework for RS and telemetry, we were able to describe that vegetation cover, soil texture, and climatic variables influence D. merriami's functional connectivity at a microgeographic scale, patterns we could further explain based on the home range, habitat use, and activity observed between sexes. We describe the relationship between environmental features and some aspects of D. merriami's behavior and physiology."
publication: ECOLOGY AND EVOLUTION
categories: 
  - desert ecosystems
  - Dipodomys merriami
  - functional connectivity
  - landscape genetics
  - Merriam's kangaroo rat
  - resistance surfaces
doi: "10.1002/ece3.4762"
url_pdf: "https://drive.google.com/open?id=1bLlyq2QLlLoJnZQhP9FL8cHCEVoVgH3"
featured: featured.png
respository_url: https://github.com/dyerlab/DLabWebsite
output:
  distill::distill_article:
    self_contained: false
---


Sampling Scheme

![Figure 1: Study site and sampling locations for Dipodomys merriami individuals on the Mapimí Biosphere Reserve, Mexico. Black triangles correspond to the trapping webs (most external points), which are projected on a grayscale aerial picture of the study site, where gray shades are vegetation patches. The three vegetation transects are depicted, separated by approximately 200 m, where we placed five trapping webs per transect, separated 50 m from each other. Each web consisted of four 25‐m lines radiating from a central point (often a Dipodomys merriami burrow). The dominant vegetation per transect is depicted with different colors and a corresponding photograph (at the bottom). For more detail, see Supporting Information Figure S1 in Supplementary Information](./fig-1.jpg)