project:
  type: website

website:
  title: "dyerlab"
  navbar:
    right:
      - href: people.qmd
        text: People
      - href: manuscripts.qmd
        text: Manuscripts
      - icon: github
        href: https://github.com/dyerlab/
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/dyerlab/
        aria-label: Twitter
  twitter-card:
    creator: "@dyerlab"    
    site: "@dyerlab"
  open-graph: 
    site-name: dyerlab

execute:
  freeze: auto

format:
  html:
    theme: 
      light: cosmo
      dark: cyborg
    css: styles.css



