project:
  type: website
website:
  title: "dyerlab"
  site-url: "https://dyerlab.org"
  navbar:
    right:
      - href: people.qmd
        text: People
      - href: manuscripts.qmd
        text: Manuscripts
      - icon: github
        href: https://github.com/dyerlab/
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/dyerlab/
        aria-label: Twitter
  twitter-card: true
execute:
  freeze: auto
format:
  html:
    theme: sandstone
    css: styles.css



