project:
  type: website

website:
  title: "dyerlab"
  navbar:
    right:
      - href: people.qmd
        text: People
      - href: manuscripts.qmd
        text: Manuscripts
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  twitter-card:
    creator: "@RodneyDyer"    
    site: "@dyerlab"
  open-graph: true
format:
  html:
    theme: cosmo
    css: styles.css



