---
title: Patterns of mating in an insect-pollinated tree species in the Missouri Ozark Forest
  Ecosystem Project
date: '2002-01-01'
authors:
- name: Victoria Apsit
- name: Rodney Dyer
- name: Victoria Sork
description: |
    PROCEEDINGS OF THE SECOND MISSOURI OZARK FOREST ECOSYSTEM PROJECT SYMPOSIUM - POST-TREATMENT RESULTS OF THE LANDSCAPE EXPERIMENT. 2002.  
preview: featured.png
journal:  PROCEEDINGS OF THE SECOND MISSOURI OZARK FOREST ECOSYSTEM PROJECT SYMPOSIUM - POST-TREATMENT RESULTS OF THE LANDSCAPE EXPERIMENT
bibliography: bibliography.bib
repository_url: https://github.com/dyerlab/DLabWebsite
output:
 distill::distill_article:
  self_contained: no
---



## Abstract

Contemporary gene flow is a major mechanism for the maintenance of genetic diversity. One component of gene flow is the mating system, which is a composite measure of selfing, mating with relatives, and outcrossing. Although both gene flow and mating patterns contribute to the ecological sustainability of populations, a focus of many forest management plans, these processes are often overlooked in forest management studies. As part of the Missouri Ozark Forest Ecosystem Project (MOFEP) we conducted a study of mating patterns in flowering dogwood (Cornus florida L), an insect-pollinated tree that is abundant and ubiquitous under story tree of upland Missouri Ozark forests. In 1998 and 1999, we collected fruit from over 200 Cornus florida individuals located in six compartments (MOFEP sites 1-6; similar to250-500 ha each), which were subjected to one of three management treatments: even-aged, uneven-aged, and no harvest. To see whether the management treatments influenced tree density surrounding the study trees, we measured and compared tree density across treatments. Because differential germination could reflect either genetic or environmental factors affecting the mating system, we measured germination success on a per maternal tree basis. We then measured the outcrossing rate, the rate of consanguineous mating (mating with relatives), and the effective number of pollen donors for each of the six sites and tested the hypotheses that both treatment and local tree density have no influence on these aspects of mating. Furthermore, the percent germination among mothers was not significantly influenced by the application of forest treatments. Multilocus outcrossing, t(m) (range 0.981-1.000), single locus outcrossing, t(s) (range 0.976-0.996), and the genetic effective number of pollen donors (range 4-11) did not differ among management treatments. For 1998, mating with relatives tended to increase with local density (df=1,28, F=4.07, P=0.053, 1998 only), suggesting local familial structure at the site level. No trend in consanguineous mating was observed in the data collected in 1999. The overall results show that the first cycle of timber harvesting had little effect on insect-mediated pollen movement in C. florida This lack of impact could be due to the fact that the treatments did not alter pollinator behavior. Thus, to evaluate the general impact of forest management on gene flow and mating in woody plants, we recommend ongoing monitoring as management treatments are continued and further studies on additional plant species.
